### ISSUE TITLE
When dcp group name includes . (dot), couchbase saves it as subdocument

### ISSUE THREAD

**Issue by kaygoren** [Trendyol/go-dcp-kafka#67]
We gave groupName as `globalplatforms.wholesale-cb-kafka-connector`, and it is occured as a subdocument in the couchbase checkpoint collection.
<img width="552" alt="image" src="https://github.com/Trendyol/go-dcp-kafka/assets/27616449/3185b3bb-1a49-4d21-bae0-55f80dd37fe0">

We need to develop to handle escape characters

**Comment by oguzyildirim** [comment]
Hello @kaygoren which go-dcp-kafka version are you using?

**Comment by kaygoren** [comment]
@oguzyildirim hi, we are using v1.1.0 which is currently latest, sorry for the missing info.

**Comment by oguzyildirim** [comment]
Greetings @kaygoren. In our checkpoint management process, we're making use of Couchbase's sub-document feature. This functionality allows us to work with sub-documents using a path syntax. As you pointed out, when a "." is included in the group name, Couchbase generates a sub-document automatically. To achieve your desired outcome, we'll need to make some modifications during generation, such as replacing dots with commas or semicolons. What do you guys think about it  @mhmtszr @Abdulsametileri @erayarslan?

**Comment by erayarslan** [comment]
thanks to @oguzyildirim, we fixed with https://github.com/Trendyol/go-dcp-kafka/commit/42e8ef4158703fce79c5ae07869e4747768252d2
