### ISSUE TITLE
Add struct passing functionality for connector config when calling NewConnectorWithLoggers

### ISSUE THREAD

**Issue by oguzgocmen** [Trendyol/go-dcp-kafka#70]
**Is your feature request related to a problem? Please describe.**
Right now if we want to initialize a new connector with loggers by passing a configPath we can but we can not pass a connector config struct. 

**Describe the solution you'd like**
configPath param in NewConnectorWithLoggers can be changed from string to any.

**Comment by oguzyildirim** [comment]
Thank you for mention  it but we have added builder support with this(https://github.com/Trendyol/go-dcp-kafka/pull/61) pull request so that we won't have any NewConnectorWithLoggers  anymore

**Comment by oguzgocmen** [comment]
Ah okey then thanks for the info and hard work🙏🏻 Closing this issue.
