### ISSUE TITLE
Get document from destination bucket 

### ISSUE THREAD

**Issue by merveyalcinkocakty** [Trendyol/go-dcp-kafka#79]
**Is your feature request related to a problem? Please describe.**
We will feed one bucket with Eventing. When the event received, we want to check a record in that bucket to see if a specific field has not been updated. Therefore, we need to fetch the relevant document from the destination bucket and make a comparison

**Describe the solution you'd like**
We want to able to get document from destination bucket

**Comment by mhmtszr** [comment]
You can do it in the mapper I think.

**Comment by merveyalcinkocakty** [comment]
I want to access the Couchbase client from the mapper without reopening the connection

**Comment by erayarslan** [comment]
released with [v1.1.21](https://github.com/Trendyol/go-dcp-couchbase/releases/tag/v1.1.21) on couchbase connector
